import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'Max',
      email: 'admin@example.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: true,
      isSeller: true,
      seller: {
        name: 'Max&Brothers',
        logo: '/images/logo1.jpg',
        description: 'best seller',
        rating: 4.5,
        numReviews: 120,
      },
    },
    {
      name: 'John',
      email: 'user@example.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: 'PlayStation 5',
      category: 'Ігрові приставки',
      image: '/product.img/playstation5.jpg',
      price: 16000,
      countInStock: 1,
      brand: 'Sony',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'Asus VivoBook Pro 17"',
      category: 'Ноутбуки',
      image: '/product.img/notebook.jpg',
      price: 20000,
      brand: 'Asus',
      countInStock: 1,
      rating: 4.0,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'Philips 55" Ambilight',
      category: 'ТВ',
      image: '/product.img/tv.jpg',
      price: 12500,
      brand: 'Philips',
      countInStock: 0,
      rating: 4.8,
      numReviews: 17,
      description: 'high quality product',
    },
    {
      name: 'RAM hunix 2gb',
      category: 'Аксесуари для ПК',
      image: '/product.img/ram.jpg',
      price: 200,
      brand: 'hunix',
      countInStock: 15,
      rating: 4.5,
      numReviews: 14,
      description: 'high quality product',
    },
    {
      name: 'ASUS GeForce GTX 1060',
      category: 'Аксесуари для ПК',
      image: '/product.img/graphiccard.jpg',
      price: 9500,
      brand: 'Asus',
      countInStock: 5,
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'Apple Airpods pro',
      category: 'Навушники',
      image: '/product.img/airpods.jpg',
      price: 3000,
      brand: 'Apple',
      countInStock: 12,
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
    },
  ],
};
export default data;
